2024-06-25 00:36:34.321935: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-06-25 00:36:34.324810: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-25 00:36:34.392173: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-25 00:36:34.392906: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 AVX_VNNI AMX_TILE AMX_INT8 AMX_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-25 00:36:35.896377: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-06-25 00:36:43.185786: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1956] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
Traceback (most recent call last):
  File "test.py", line 166, in <module>
    main(args.student_id)
  File "test.py", line 129, in main
    game_results = play_games(student_id, student_ai, f'baseline{i}', baseline_ai)
  File "test.py", line 90, in play_games
    game_result = start_poker(config, verbose=1, decks=decks[j])
  File "/home/ubitus03/fai_final_project/game/game.py", line 16, in start_poker
    result_message = dealer.start_game(config.max_round, decks)
  File "/home/ubitus03/fai_final_project/game/engine/dealer.py", line 33, in start_game
    self.__notify_game_start(max_round)
  File "/home/ubitus03/fai_final_project/game/engine/dealer.py", line 98, in __notify_game_start
    self.message_handler.process_message(-1, start_msg)
  File "/home/ubitus03/fai_final_project/game/engine/dealer.py", line 229, in process_message
    receiver.receive_notification(msg["message"])
  File "/home/ubitus03/fai_final_project/game/players.py", line 73, in receive_notification
    self.receive_game_start_message(info)
  File "/home/ubitus03/fai_final_project/./b11705026/agent.py", line 167, in receive_game_start_message
    self.load_model(MODEL_PATH)
  File "/home/ubitus03/fai_final_project/./b11705026/agent.py", line 204, in load_model
    self.agent.load(path)
  File "/home/ubitus03/fai_final_project/./b11705026/DQN_agent.py", line 59, in load
    self.model.load_weights(name)
  File "/home/ubitus03/miniconda3/envs/poker/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/ubitus03/miniconda3/envs/poker/lib/python3.8/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/ubitus03/miniconda3/envs/poker/lib/python3.8/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = './train data/dqn_poker_model_3raise_200_all.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
